# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nigCpp <- function(x, y, a1, a2, b1, b2, b3, theta, pi) {
    .Call(`_briskaR_nigCpp`, x, y, a1, a2, b1, b2, b3, theta, pi)
}

geometricCpp <- function(x, y, aa, pi) {
    .Call(`_briskaR_geometricCpp`, x, y, aa, pi)
}

FatTailCpp <- function(x, y, a, b) {
    .Call(`_briskaR_FatTailCpp`, x, y, a, b)
}

studentCpp <- function(x, y, a, b, c1, c2, theta, pi) {
    .Call(`_briskaR_studentCpp`, x, y, a, b, c1, c2, theta, pi)
}

shift_fft_Cpp <- function(xx) {
    .Call(`_briskaR_shift_fft_Cpp`, xx)
}

